<a href="https://colab.research.google.com/github/gracenaomi1122/my-first-repo/blob/main/Assignment_Numerical_Computing_with_NumPy_Subjective.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

#Task 1
#Generate and Inspect the Dataset

#Set seed
np.random.seed(42)

#List of names
names_list = ["Alice", "Bob", "Charlie", "David", "Emma"]

#Generate data for 10 students
names = np.random.choice(names_list, 10)
ages = np.random.randint(15, 19, 10)

maths = np.random.randint(40, 101, 10)
science = np.random.randint(40, 101, 10)
english = np.random.randint(40, 101, 10)

#Creating marks array
marks = np.column_stack((maths, science, english))

#Print shape and dtype
print("Marks Array:\n", marks)
print("\nShape of marks array:", marks.shape)
print("Data type of marks array:", marks.dtype)

#Task 2 — Reshape and Slice the Marks Array

#Reshape array
reshaped_marks = marks.reshape(2, 5, 3)

print("\nReshaped Array (2, 5, 3):\n", reshaped_marks)

#Slice first five students for maths and science only
slice_marks = marks[:5, 0:2]

print("\nFirst five students (Maths & Science only):\n", slice_marks)


#Task 3 — Save Records to a File

with open("student_records.txt", "w") as file:
    for i in range(10):
        record = f"{names[i]} | {ages[i]} | {maths[i]} | {science[i]} | {english[i]}\n"
        file.write(record)

print("\nRecords successfully written to student_records.txt")

#Read and print file contents
print("\nContents of student_records.txt:\n")

with open("student_records.txt", "r") as file:
    lines = file.readlines()
    for line in lines:
        print(line.strip())

Marks Array:
 [[ 77  64  90]
 [ 41  88  83]
 [ 99  66  94]
 [ 60  98  91]
 [ 72  81  96]
 [ 51  67  42]
 [ 97  99  76]
 [ 61  55  90]
 [100  54  46]
 [ 83  86  60]]

Shape of marks array: (10, 3)
Data type of marks array: int64

Reshaped Array (2, 5, 3):
 [[[ 77  64  90]
  [ 41  88  83]
  [ 99  66  94]
  [ 60  98  91]
  [ 72  81  96]]

 [[ 51  67  42]
  [ 97  99  76]
  [ 61  55  90]
  [100  54  46]
  [ 83  86  60]]]

First five students (Maths & Science only):
 [[77 64]
 [41 88]
 [99 66]
 [60 98]
 [72 81]]

Records successfully written to student_records.txt

Contents of student_records.txt:

David | 18 | 77 | 64 | 90
Emma | 18 | 41 | 88 | 83
Charlie | 18 | 99 | 66 | 94
Emma | 17 | 60 | 98 | 91
Emma | 16 | 72 | 81 | 96
Bob | 15 | 51 | 67 | 42
Charlie | 16 | 97 | 99 | 76
Charlie | 18 | 61 | 55 | 90
Charlie | 18 | 100 | 54 | 46
Emma | 16 | 83 | 86 | 60


In [3]:
import numpy as np

np.random.seed(42)

# ── Task 1: Generate and Inspect the Dataset ──────────────────────────────────
names   = np.random.choice(['Alice', 'Bob', 'Carol', 'David', 'Eva'], size=10)
ages    = np.random.randint(15, 19, size=10)
maths   = np.random.randint(40, 101, size=10)
science = np.random.randint(40, 101, size=10)
english = np.random.randint(40, 101, size=10)

marks = np.array([maths, science, english]).T   # shape (10, 3)

print("Marks array shape :", marks.shape)
print("Marks array dtype :", marks.dtype)

# ── Task 2: Reshape and Slice ─────────────────────────────────────────────────
reshaped = marks.reshape(2, 5, 3)
print("\nReshaped marks array (2, 5, 3):")
print(reshaped)

sliced = marks[:5, :2]
print("\nFirst 5 students — Maths and Science only:")
print(sliced)

# Shape (2, 5, 3) means the 10 student records are divided into 2 groups,
# each group containing 5 students, and each student has 3 subject marks.
# It is like splitting the class into 2 batches of 5 students each.

# ── Task 3: Save Records to File ─────────────────────────────────────────────
with open('student_records.txt', 'w') as f:
    for i in range(10):
        line = f"{names[i]} | {ages[i]} | {maths[i]} | {science[i]} | {english[i]}\n"
        f.write(line)

print("\nRecords written to student_records.txt")

with open('student_records.txt', 'r') as f:
    lines = f.readlines()

print("\nVerification — File Contents:")
for line in lines:
    print(line.strip())

Marks array shape : (10, 3)
Marks array dtype : int64

Reshaped marks array (2, 5, 3):
[[[ 77  64  90]
  [ 41  88  83]
  [ 99  66  94]
  [ 60  98  91]
  [ 72  81  96]]

 [[ 51  67  42]
  [ 97  99  76]
  [ 61  55  90]
  [100  54  46]
  [ 83  86  60]]]

First 5 students — Maths and Science only:
[[77 64]
 [41 88]
 [99 66]
 [60 98]
 [72 81]]

Records written to student_records.txt

Verification — File Contents:
David | 18 | 77 | 64 | 90
Eva | 18 | 41 | 88 | 83
Carol | 18 | 99 | 66 | 94
Eva | 17 | 60 | 98 | 91
Eva | 16 | 72 | 81 | 96
Bob | 15 | 51 | 67 | 42
Carol | 16 | 97 | 99 | 76
Carol | 18 | 61 | 55 | 90
Carol | 18 | 100 | 54 | 46
Eva | 16 | 83 | 86 | 60
